# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-slim

WORKDIR /app

# Copy all project files
COPY . .

# Install dependencies and package
RUN pip install --upgrade pip && \
    pip install --no-cache-dir .

# Expose default graphQL port if needed
EXPOSE 10101

# Entrypoint for MCP stdio server
ENTRYPOINT ["mvf1-cli", "mcp"]
